# Generated by Django 5.2 on 2025-04-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('jg', '중구'), ('gr', '구로구'), ('ep', '은평구'), ('mp', '마포구'), ('gn', '강남구'), ('sd', '성동구'), ('yd', '영등포구'), ('ys', '용산구'), ('gb', '강북구'), ('sb', '성북구'), ('gd', '강동구'), ('jn', '종로구'), ('db', '도봉구'), ('yc', '양천구'), ('nw', '노원구'), ('jr', '중랑구'), ('gj', '광진구'), ('dd', '동대문구'), ('sm', '서대문구'), ('gc', '금천구'), ('gs', '강서구'), ('sc', '서초구'), ('ga', '관악구'), ('dj', '동작구'), ('sp', '송파구')], max_length=10, verbose_name='District')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=11)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('district', 'lat', 'lot', 'addr'), ('lat', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeName', models.CharField(max_length=255, verbose_name='OfficeName')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=11)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('lat', 'lot'), ('officeName', 'lat', 'lot', 'addr')},
            },
        ),
    ]
