# Generated by Django 5.2 on 2025-04-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('001', '경찰서'), ('002', 'CCTV'), ('003', '안전시설물'), ('004', '안전지킴이집')], max_length=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=11)),
                ('addr', models.CharField(blank=True, max_length=255, null=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='OfficeName')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('301', '안심벨'), ('302', 'CCTV'), ('303', '안내표지판 (전주 표기 포함)'), ('304', '노면표기'), ('305', '보안등'), ('306', '안심귀갓길 서비스 안내판'), ('307', '112 위치 신고 안내판'), ('308', '기타(안심반사경 등)')], default='301', max_length=10)),
                ('facility_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('facility_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('facility_location', models.TextField()),
                ('sigungu_code', models.CharField(max_length=20)),
                ('sigungu_name', models.CharField(max_length=20)),
                ('eupmyeondong_code', models.CharField(max_length=20)),
                ('eupmyeondong_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('401', '택배함'), ('402', '지킴이집'), ('403', '기타 서비스')], default='401', max_length=10)),
                ('service_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('service_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('service_location', models.TextField()),
                ('sigungu_code', models.CharField(max_length=20)),
                ('sigungu_name', models.CharField(max_length=20)),
                ('eupmyeondong_code', models.CharField(max_length=20)),
                ('eupmyeondong_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='OfficeName')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(choices=[('jg', '중구'), ('gr', '구로구'), ('ep', '은평구'), ('mp', '마포구'), ('gn', '강남구'), ('sd', '성동구'), ('yd', '영등포구'), ('ys', '용산구'), ('gb', '강북구'), ('sb', '성북구'), ('gd', '강동구'), ('jn', '종로구'), ('db', '도봉구'), ('yc', '양천구'), ('nw', '노원구'), ('jr', '중랑구'), ('gj', '광진구'), ('dd', '동대문구'), ('sm', '서대문구'), ('gc', '금천구'), ('gs', '강서구'), ('sc', '서초구'), ('ga', '관악구'), ('dj', '동작구'), ('sp', '송파구')], max_length=10, verbose_name='District')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=11)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('district', 'lat', 'lot', 'addr'), ('lat', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='PoliceOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=255, verbose_name='OfficeName')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lot', models.DecimalField(decimal_places=8, max_digits=11)),
                ('addr', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('lat', 'lot'), ('office_name', 'lat', 'lot', 'addr')},
            },
        ),
    ]
