# Generated by Django 5.2 on 2025-04-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('301', '안심벨'), ('302', 'CCTV'), ('303', '안내표지판 (전주 표기 포함)'), ('304', '노면표기'), ('305', '보안등'), ('306', '안심귀갓길 서비스 안내판'), ('307', '112 위치 신고 안내'), ('308', '기타(안심반사경 등)')], default='301', max_length=10)),
                ('facility_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('facility_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('facility_location', models.TextField()),
                ('sigungu_code', models.CharField(max_length=20)),
                ('sigungu_name', models.CharField(max_length=20)),
                ('eupmyeondong_code', models.CharField(max_length=20)),
                ('eupmyeondong_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=50, unique=True)),
                ('service_type', models.CharField(choices=[('401', '택배함'), ('402', '지킴이집'), ('403', '기타 서비스')], default='401', max_length=10)),
                ('service_latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('service_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('service_location', models.TextField()),
                ('sigungu_code', models.CharField(max_length=20)),
                ('sigungu_name', models.CharField(max_length=20)),
                ('eupmyeondong_code', models.CharField(max_length=20)),
                ('eupmyeondong_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
