# Generated by Django 5.2 on 2025-04-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayicon',
            old_name='office_name',
            new_name='officeName',
        ),
    ]
