# Generated by Django 5.2 on 2025-04-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0002_rename_office_name_displayicon_officename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='displayicon',
            old_name='facility_type',
            new_name='facilityType',
        ),
    ]
