# Generated by Django 5.2 on 2025-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi', '0003_rename_facility_type_displayicon_facilitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='displayicon',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policeoffice',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policeoffice',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
