# Generated by Django 5.2 on 2025-04-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_rename_requester_relation_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='childName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='relation',
            name='parentName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
