# Generated by Django 5.2 on 2025-04-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
