# Generated by Django 5.2 on 2025-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_deleted_at_customuser_fcmtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
