# Generated by Django 5.2 on 2025-04-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcmToken',
            field=models.TextField(blank=True, null=True),
        ),
    ]
