# Generated by Django 5.2 on 2025-04-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_fcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fcmToken',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
