# Generated by Django 5.2 on 2025-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_profilename_customuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
